begin;
select plan(28);
\ir actor_accept_fixture.sql
select ok(not has_function_privilege('anon','public.accept_tow_offer(uuid,uuid)','EXECUTE'),'legacy anonymous accept revoked');
select ok(not has_function_privilege('authenticated','public.accept_tow_offer(uuid,uuid)','EXECUTE'),'legacy client accept revoked');
select ok(not has_function_privilege('service_role','public.accept_tow_offer(uuid,uuid)','EXECUTE'),'legacy actorless service accept revoked');
select ok(not has_function_privilege('anon','public.accept_tow_offer_for_actor(uuid,uuid,uuid,text)','EXECUTE'),'anonymous actor RPC revoked');
select ok(not has_function_privilege('authenticated','public.accept_tow_offer_for_actor(uuid,uuid,uuid,text)','EXECUTE'),'client actor RPC revoked');
select throws_ok($q$ select * from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,null,'test') $q$,'42501','identified_driver_actor_required','missing actor fails');
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-2')::uuid,'test')),'forbidden','wrong actor fails');
update public.tenant_users set status='suspended' where user_id=md5('f1-user-1')::uuid;
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'test')),'forbidden','suspended member fails');
update public.tenant_users set status='active' where user_id=md5('f1-user-1')::uuid;
update public.tow_drivers set status='inactive' where id=md5('f1-driver-1')::uuid;
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'test')),'forbidden','inactive driver fails');
update public.tow_drivers set status='active' where id=md5('f1-driver-1')::uuid;
update public.tow_vehicle_insurance_permissions set status='suspended' where tow_vehicle_id=md5('f1-vehicle-1')::uuid;
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'test')),'vehicle_not_approved','revoked vehicle cannot accept old offer');
update public.tow_vehicle_insurance_permissions set status='active' where tow_vehicle_id=md5('f1-vehicle-1')::uuid;
select is((select accepted from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'test')),true,'valid driver accepts');
select is((select count(*)::integer from public.tow_job_assignments),1,'one assignment');
select is((select count(*)::integer from public.tow_job_customer_shares),1,'one share');
select is((select count(*)::integer from public.tow_job_status_events),1,'one status event');
select is((select count(*)::integer from public.audit_logs where action='tow.driver_accepted'),1,'one attributed audit');
select is((select count(*)::integer from public.webhook_deliveries),1,'one webhook intent');
select is((select count(*)::integer from public.notification_deliveries where tow_job_id is not null),1,'one accept email intent');
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-1')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'retry')),'already_accepted_by_driver','retry returns winner');
select is((select count(*)::integer from public.webhook_deliveries),1,'retry has no duplicated webhook');
select is((select count(*)::integer from public.tow_job_customer_shares),1,'retry has no duplicated share');
select is((select reason from public.accept_tow_offer_for_actor(md5('f1-job-2')::uuid,md5('f1-driver-1')::uuid,md5('f1-user-1')::uuid,'other')),'resource_busy','same driver cannot reserve another job');
select set_config('request.jwt.claim.sub',md5('f1-user-1')::text,true);
set local role authenticated;
select is((select count(*)::integer from public.tow_job_customer_shares),1,'current driver can read contact');
reset role;
select set_config('request.jwt.claim.sub',md5('f1-user-2')::text,true);
set local role authenticated;
select is((select count(*)::integer from public.tow_job_customer_shares),0,'losing driver cannot read contact');
reset role;
update public.tow_jobs set status='completed' where id=md5('f1-job-1')::uuid;
select set_config('request.jwt.claim.sub',md5('f1-user-1')::text,true);
set local role authenticated;
select is((select count(*)::integer from public.tow_job_customer_shares),0,'completion revokes operational contact');
select throws_ok($q$ update public.user_profiles set is_platform_admin=true where id=md5('f1-user-1')::uuid $q$,'42501',null,'self promotion is denied');
reset role;
create function pg_temp.fail_outbox() returns trigger language plpgsql as $$ begin raise exception 'injected_outbox_failure'; end $$;
create trigger test_outbox_failure before insert on public.webhook_deliveries for each row execute function pg_temp.fail_outbox();
select throws_ok($q$ select * from public.accept_tow_offer_for_actor(md5('f1-job-3')::uuid,md5('f1-driver-3')::uuid,md5('f1-user-3')::uuid,'rollback') $q$,'P0001','injected_outbox_failure','outbox failure rolls back accept');
select is((select status::text from public.tow_jobs where id=md5('f1-job-3')::uuid),'offered','job not falsely accepted');
select is((select count(*)::integer from public.tow_job_customer_shares where tow_job_id=md5('f1-job-3')::uuid),0,'rollback leaves no share');
select * from finish();
rollback;
